AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: A function based game server manager
Resources:
  ManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
  ChangeServerStateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api/change-server-state
      Handler: ./api/change-server-state/index.handler
      Runtime: nodejs18.x
      Description: Start and stop Valhalla servers
      Timeout: 10
      Role: arn:aws:iam::916874177440:role/valhalla-lambda
      FunctionName: valhalla-change-server-state
      Events:
        Api:
          Type: Api
          Properties:
            Path: /valhalla/state
            Method: post
            RestApiId: !Ref ManagementApi
  GetServerStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api/get-server-status
      Handler: ./api/get-server-status/index.handler
      Runtime: nodejs18.x
      Description: Get state and details of Valhalla instances and servers
      Timeout: 10
      Role: arn:aws:iam::916874177440:role/valhalla-lambda
      FunctionName: valhalla-get-server-status
      Events:
        Api:
          Type: Api
          Properties:
            Path: /valhalla/status
            Method: get
            RestApiId: !Ref ManagementApi
      # VpcConfig:
      #   SecurityGroupIds:
      #     - sg-08806ce8e56dea70b
      #   SubnetIds:
      #     - subnet-0708e65042f6fecfd
  GetInternalServerStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api/get-internal-server-status
      Handler: ./api-get-internal-server-status/index.handler
      Runtime: nodejs18.x
      Description: Get details of Valhalla servers internal to the instances
      Timeout: 10
      Role: arn:aws:iam::916874177440:role/valhalla-lambda
      FunctionName: valhalla-get-internal-server-status
      VpcConfig:
        SecurityGroupIds:
          - sg-08806ce8e56dea70b
        SubnetIds:
          - subnet-060715bd6c442feec
