AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A serverless application to toggle instance state
Resources:
  ManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
  ServerStateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: server-state/index.handler
      Runtime: nodejs12.x
      Description: Instance state function
      Timeout: 10
      Role: arn:aws:iam::916874177440:role/valhalla-lambda
      FunctionName: valhalla-server-state
      Events: 
        Api:
          Type: Api
          Properties:
            Path: /valhalla/servers/{serverId}/state/{state}
            Method: post
            RestApiId: !Ref ManagementApi
  ServerStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: server-status/index.handler
      Runtime: nodejs12.x
      Description: Server status function
      Timeout: 10
      Role: arn:aws:iam::916874177440:role/valhalla-lambda
      FunctionName: valhalla-server-status
      Events:
        Api:
          Type: Api
          Properties:
            Path: /valhalla/servers/{serverId}/state
            Method: get
            RestApiId: !Ref ManagementApi
  ServerDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: server-details/index.handler
      Runtime: nodejs12.x
      Description: Server details function
      Timeout: 10
      Role: arn:aws:iam::916874177440:role/valhalla-lambda
      FunctionName: valhalla-server-details
      VpcConfig:
        SecurityGroupIds:
          - sg-08806ce8e56dea70b
        SubnetIds:
          - subnet-060715bd6c442feec
      Events:
        Api:
          Type: Api
          Properties:
            Path: /valhalla/servers/server-ip/{serverIp}/details
            Method: get
            RestApiId: !Ref ManagementApi
  ShutdownMonitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: shutdown-monitor/index.handler
      Runtime: nodejs12.x
      Description: Shutdown monitor function
      Timeout: 60
      Role: arn:aws:iam::916874177440:role/valhalla-lambda
      FunctionName: valhalla-shutdown-monitor
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *)