AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A serverless application to collect server status
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Description: Server status function
      Timeout: 10
      Role: arn:aws:iam::916874177440:role/valhalla-lambda
      FunctionName: valhalla-server-status
      VpcConfig:
        SecurityGroupIds:
          - sg-08806ce8e56dea70b
        SubnetIds:
          - subnet-060715bd6c442feec
      Events:
        Api:
          Type: Api
          Properties:
            Path: /valhalla/state
            Method: get
