AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A serverless application to toggle instance state
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Description: Instance state function
      Timeout: 180
      Role: arn:aws:iam::916874177440:role/valhalla-lambda
      FunctionName: valhalla-server-state
      Events: 
        Api:
          Type: Api
          Properties:
            Path: /valhalla/state/{state}
            Method: post